<?php
/**
 * ProductDetailsResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Axesso Api
 *
 * Use this api to fetch information to Amazon products and more.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@axesso.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ProductDetailsResponseTest Class Doc Comment
 *
 * @category    Class
 * @description ProductDetailsResponse
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductDetailsResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProductDetailsResponse"
     */
    public function testProductDetailsResponse()
    {
    }

    /**
     * Test attribute "response_status"
     */
    public function testPropertyResponseStatus()
    {
    }

    /**
     * Test attribute "response_message"
     */
    public function testPropertyResponseMessage()
    {
    }

    /**
     * Test attribute "product_title"
     */
    public function testPropertyProductTitle()
    {
    }

    /**
     * Test attribute "manufacturer"
     */
    public function testPropertyManufacturer()
    {
    }

    /**
     * Test attribute "count_review"
     */
    public function testPropertyCountReview()
    {
    }

    /**
     * Test attribute "answered_questions"
     */
    public function testPropertyAnsweredQuestions()
    {
    }

    /**
     * Test attribute "product_rating"
     */
    public function testPropertyProductRating()
    {
    }

    /**
     * Test attribute "asin"
     */
    public function testPropertyAsin()
    {
    }

    /**
     * Test attribute "size_selection"
     */
    public function testPropertySizeSelection()
    {
    }

    /**
     * Test attribute "sold_by"
     */
    public function testPropertySoldBy()
    {
    }

    /**
     * Test attribute "fulfilled_by"
     */
    public function testPropertyFulfilledBy()
    {
    }

    /**
     * Test attribute "warehouse_availability"
     */
    public function testPropertyWarehouseAvailability()
    {
    }

    /**
     * Test attribute "retail_price"
     */
    public function testPropertyRetailPrice()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "price_shipping_information"
     */
    public function testPropertyPriceShippingInformation()
    {
    }

    /**
     * Test attribute "price_saving"
     */
    public function testPropertyPriceSaving()
    {
    }

    /**
     * Test attribute "features"
     */
    public function testPropertyFeatures()
    {
    }

    /**
     * Test attribute "prime"
     */
    public function testPropertyPrime()
    {
    }

    /**
     * Test attribute "product_description"
     */
    public function testPropertyProductDescription()
    {
    }
}
