<?php
/**
 * SortOptionResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Axesso Api
 *
 * Use this api to fetch information to Amazon products and more.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@axesso.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SortOptionResponseTest Class Doc Comment
 *
 * @category    Class
 * @description SortOptionResponse
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SortOptionResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SortOptionResponse"
     */
    public function testSortOptionResponse()
    {
    }

    /**
     * Test attribute "response_status"
     */
    public function testPropertyResponseStatus()
    {
    }

    /**
     * Test attribute "response_message"
     */
    public function testPropertyResponseMessage()
    {
    }

    /**
     * Test attribute "result_size"
     */
    public function testPropertyResultSize()
    {
    }

    /**
     * Test attribute "sort_options"
     */
    public function testPropertySortOptions()
    {
    }
}
